"""
Export docking results to professional visualization formats.

Supported formats:
- PyMOL (.pse, .pml)
- Chimera (.py)
- VMD (.tcl)
"""

from pathlib import Path
from typing import List, Optional, Dict
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def create_pymol_script(
    protein_pdb: str,
    ligand_pdbqt: str,
    output_path: str,
    ligand_name: str = "ligand",
    show_pocket: bool = True,
    pocket_radius: float = 5.0
) -> str:
    """
    Create PyMOL script (.pml) for visualization.

    Args:
        protein_pdb: Path to protein PDB file
        ligand_pdbqt: Path to ligand PDBQT file
        output_path: Where to save .pml script
        ligand_name: Name for ligand object
        show_pocket: Highlight binding pocket
        pocket_radius: Radius around ligand for pocket

    Returns:
        Path to created script
    """
    script_lines = [
        "# PyMOL Visualization Script",
        "# Generated by Digital CRO Platform",
        "",
        "# Clear workspace",
        "reinitialize",
        "",
        "# Load protein",
        f"load {protein_pdb}, protein",
        "",
        "# Load ligand",
        f"load {ligand_pdbqt}, {ligand_name}",
        "",
        "# Protein representation",
        "hide everything, protein",
        "show cartoon, protein",
        "color gray, protein",
        "set cartoon_transparency, 0.3, protein",
        "",
        "# Ligand representation",
        f"hide everything, {ligand_name}",
        f"show sticks, {ligand_name}",
        f"color green, {ligand_name}",
        f"set stick_radius, 0.15, {ligand_name}",
        "",
    ]

    if show_pocket:
        script_lines.extend([
            "# Highlight binding pocket",
            f"select pocket, protein within {pocket_radius} of {ligand_name}",
            "show sticks, pocket",
            "color orange, pocket",
            "set stick_radius, 0.2, pocket",
            "",
        ])

    script_lines.extend([
        "# Center view on ligand",
        f"center {ligand_name}",
        f"zoom {ligand_name}, 8",
        "",
        "# Rendering settings",
        "set ray_trace_mode, 1",
        "set ray_shadows, 1",
        "bg_color white",
        "",
        "# Labels",
        f"label {ligand_name} and name C1, '{ligand_name}'",
        "",
        "# Done",
        "print 'Visualization loaded successfully!'",
    ])

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w') as f:
        f.write('\n'.join(script_lines))

    logger.info(f"✓ PyMOL script created: {output_path}")

    return str(output_path)


def create_pymol_session_files(
    protein_pdb: str,
    ligand_pdbqts: List[str],
    output_dir: str,
    ligand_names: Optional[List[str]] = None
) -> List[str]:
    """
    Create PyMOL scripts for multiple ligands.

    Args:
        protein_pdb: Path to protein PDB
        ligand_pdbqts: List of ligand PDBQT files
        output_dir: Output directory
        ligand_names: Names for each ligand

    Returns:
        List of created script paths
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if ligand_names is None:
        ligand_names = [f"ligand_{i+1}" for i in range(len(ligand_pdbqts))]

    created_files = []

    # Individual scripts
    for ligand_path, name in zip(ligand_pdbqts, ligand_names):
        script_path = output_dir / f"{name}_pymol.pml"

        create_pymol_script(
            protein_pdb=protein_pdb,
            ligand_pdbqt=ligand_path,
            output_path=str(script_path),
            ligand_name=name
        )

        created_files.append(str(script_path))

    # Combined script (all ligands)
    if len(ligand_pdbqts) > 1:
        combined_script = create_pymol_combined_script(
            protein_pdb=protein_pdb,
            ligand_pdbqts=ligand_pdbqts,
            output_path=str(output_dir / "all_ligands_pymol.pml"),
            ligand_names=ligand_names
        )
        created_files.append(combined_script)

    return created_files


def create_pymol_combined_script(
    protein_pdb: str,
    ligand_pdbqts: List[str],
    output_path: str,
    ligand_names: List[str]
) -> str:
    """Create PyMOL script showing all ligands together"""

    script_lines = [
        "# PyMOL Multi-Ligand Visualization",
        "# Generated by Digital CRO Platform",
        "",
        "reinitialize",
        "",
        "# Load protein",
        f"load {protein_pdb}, protein",
        "hide everything, protein",
        "show cartoon, protein",
        "color gray, protein",
        "set cartoon_transparency, 0.5, protein",
        "",
    ]

    # Colors for multiple ligands
    colors = ['green', 'cyan', 'magenta', 'yellow', 'orange', 'purple', 'pink', 'lime']

    for idx, (ligand_path, name) in enumerate(zip(ligand_pdbqts, ligand_names)):
        color = colors[idx % len(colors)]

        script_lines.extend([
            f"# Ligand {idx+1}: {name}",
            f"load {ligand_path}, {name}",
            f"hide everything, {name}",
            f"show sticks, {name}",
            f"color {color}, {name}",
            f"set stick_radius, 0.15, {name}",
            "",
        ])

    script_lines.extend([
        "# Center view",
        "center protein",
        "zoom protein, 5",
        "",
        "bg_color white",
        "print 'Multi-ligand visualization loaded!'",
    ])

    with open(output_path, 'w') as f:
        f.write('\n'.join(script_lines))

    logger.info(f"✓ PyMOL combined script created: {output_path}")

    return str(output_path)


def create_chimera_script(
    protein_pdb: str,
    ligand_pdbqt: str,
    output_path: str,
    ligand_name: str = "ligand"
) -> str:
    """
    Create Chimera Python script for visualization.

    Args:
        protein_pdb: Path to protein PDB
        ligand_pdbqt: Path to ligand PDBQT
        output_path: Output path for script
        ligand_name: Name for ligand

    Returns:
        Path to created script
    """
    script_lines = [
        "# UCSF Chimera Visualization Script",
        "# Generated by Digital CRO Platform",
        "",
        "from chimera import runCommand as rc",
        "",
        "# Open structures",
        f"rc('open {protein_pdb}')",
        f"rc('open {ligand_pdbqt}')",
        "",
        "# Protein representation",
        "rc('~display')",
        "rc('ribbon #0')",
        "rc('color gray #0')",
        "rc('transparency 30,r #0')",
        "",
        "# Ligand representation",
        "rc('display #1')",
        "rc('represent stick #1')",
        "rc('color green #1')",
        "",
        "# Binding pocket",
        "rc('select #0 & #1 z<5')",
        "rc('display sel')",
        "rc('represent stick sel')",
        "rc('color orange sel')",
        "",
        "# Center view",
        "rc('focus #1')",
        "",
        "# Rendering",
        "rc('background solid white')",
        "rc('lighting mode two-point')",
        "",
        "print('Chimera visualization loaded!')",
    ]

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w') as f:
        f.write('\n'.join(script_lines))

    logger.info(f"✓ Chimera script created: {output_path}")

    return str(output_path)


def create_vmd_script(
    protein_pdb: str,
    ligand_pdbqt: str,
    output_path: str,
    ligand_name: str = "ligand"
) -> str:
    """
    Create VMD TCL script for visualization.

    Args:
        protein_pdb: Path to protein PDB
        ligand_pdbqt: Path to ligand PDBQT
        output_path: Output path for script
        ligand_name: Name for ligand

    Returns:
        Path to created script
    """
    script_lines = [
        "# VMD Visualization Script",
        "# Generated by Digital CRO Platform",
        "",
        "# Load structures",
        f"mol new {protein_pdb} type pdb waitfor all",
        f"mol new {ligand_pdbqt} type pdb waitfor all",
        "",
        "# Protein representation",
        "mol modstyle 0 0 NewCartoon",
        "mol modcolor 0 0 ColorID 7",
        "mol modmaterial 0 0 Transparent",
        "",
        "# Ligand representation",
        "mol modstyle 0 1 Licorice",
        "mol modcolor 0 1 ColorID 4",
        "",
        "# Binding pocket",
        "set protein [atomselect 0 protein]",
        "set ligand [atomselect 1 all]",
        "set pocket [atomselect 0 \"protein and within 5 of (index [$ligand get index])\"]",
        "",
        "mol addrep 0",
        "mol modselect 1 0 \"protein and within 5 of (index [$ligand get index])\"",
        "mol modstyle 1 0 Licorice",
        "mol modcolor 1 0 ColorID 3",
        "",
        "# Center view",
        "display resetview",
        "mol top 1",
        "display resetview",
        "",
        "# Colors and rendering",
        "color Display Background white",
        "axes location Off",
        "",
        "puts \"VMD visualization loaded!\"",
    ]

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w') as f:
        f.write('\n'.join(script_lines))

    logger.info(f"✓ VMD script created: {output_path}")

    return str(output_path)


def export_all_formats(
    protein_pdb: str,
    ligand_pdbqts: List[str],
    output_dir: str,
    ligand_names: Optional[List[str]] = None
) -> Dict[str, List[str]]:
    """
    Export to all visualization formats at once.

    Args:
        protein_pdb: Path to protein PDB
        ligand_pdbqts: List of ligand PDBQT files
        output_dir: Output directory
        ligand_names: Names for ligands

    Returns:
        Dict mapping format name to list of created files
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if ligand_names is None:
        ligand_names = [f"ligand_{i+1}" for i in range(len(ligand_pdbqts))]

    exports = {
        'pymol': [],
        'chimera': [],
        'vmd': []
    }

    # PyMOL
    pymol_dir = output_dir / "pymol"
    exports['pymol'] = create_pymol_session_files(
        protein_pdb=protein_pdb,
        ligand_pdbqts=ligand_pdbqts,
        output_dir=str(pymol_dir),
        ligand_names=ligand_names
    )

    # Chimera
    chimera_dir = output_dir / "chimera"
    chimera_dir.mkdir(exist_ok=True)

    for ligand_path, name in zip(ligand_pdbqts, ligand_names):
        script_path = create_chimera_script(
            protein_pdb=protein_pdb,
            ligand_pdbqt=ligand_path,
            output_path=str(chimera_dir / f"{name}_chimera.py"),
            ligand_name=name
        )
        exports['chimera'].append(script_path)

    # VMD
    vmd_dir = output_dir / "vmd"
    vmd_dir.mkdir(exist_ok=True)

    for ligand_path, name in zip(ligand_pdbqts, ligand_names):
        script_path = create_vmd_script(
            protein_pdb=protein_pdb,
            ligand_pdbqt=ligand_path,
            output_path=str(vmd_dir / f"{name}_vmd.tcl"),
            ligand_name=name
        )
        exports['vmd'].append(script_path)

    logger.info(f"✓ Exported to all formats: {sum(len(v) for v in exports.values())} files")

    return exports
